name = "Tango"
uuid = "06085058-b217-4503-bd57-0f340f45f217"
authors = ["Rik <rik.hoekstra@xs4all.nl> and contributors"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
